#' Azure Storage Blob Call
#'
#' Make an arbitrary request to the Storage Service. This function creates the
#' required headers to a successful request, including the Shared Signature Key
#' Authorizatoin header, which is a pain in the ass.
#'
#' @param verb
#' [character(1): required]\cr
#' A valid HTTP request
#'
#' @param storage_account
#' [character(1): required]\cr
#' Azure Storage Account
#'
#' @param storage_key
#' [character(1): required]\cr
#' Azure Storage Account Key
#'
#' @param container
#' [character(1): optional (NULL)]\cr
#' Storage Container
#'
#' @param blob
#' [character(1): optional (NULL)]\cr
#' Blob name
#'
#' @param query
#' [Named list: optional]\cr
#' Named list of query parameters to append to the URL. This is passed to
#' \code{\link{get_signature}} and \code{\link[httr]{VERB}}.
#'
#' @param xheaders
#' [Named list: optional]\cr
#' Additional HTTP headers passed to \code{\link[httr]{add_headers}}.
#' Authorization, "x-ms-date" and "x-ms-version" are generated by this function.
#'
#' @param ...
#' Further arguments passed to \code{\link[httr]{VERB}}
#'
#' @param body_content
#' [raw|character|\code{\link[curl]{form_file}}: optional]\cr
#' Object to be passed to the request body.
#'
#' @param verbose
#' [logical(1): optional]\cr
#' Should give you a verbose output? FALSE by default.
#'
#' @param URL
#' [character(1): optional]\cr
#' Forces to use the provided URL
#'
#' @return
#' \code{\link[httr]{response}} object object
#'
#' @importFrom httr VERB verbose add_headers config
#' @importFrom magrittr "%>%"
#' @importFrom checkmate assert_subset assert_character assert_list assert
#' @importFrom checkmate check_class assert_flag
#'
#' @export
azure_blob_call <- function(
  verb, storage_account, storage_key,
  container = NULL, blob = NULL,
  query = new("namedList"), xheaders = new("namedList"), ...,
  body_content = NULL, verbose = FALSE, URL = NULL
) {
  # Valid options -----------------------------------------------------------
  valid_verbs <- c("GET", "POST", "DELETE", "PUT", "HEAD")

  # Assertions
  assert_subset(verb, valid_verbs, empty.ok = FALSE)
  assert_character(storage_account, null.ok = FALSE)
  assert_character(storage_key, null.ok = FALSE)
  assert_character(container, null.ok = TRUE)
  assert_character(blob, null.ok = TRUE)
  assert_list(xheaders, any.missing = FALSE, names = "unique")
  assert(
    check_class(body_content, "form_file"), check_class(body_content, "raw"),
    check_class(body_content, "character"), check_class(body_content, "NULL")
  )
  assert_flag(verbose)
  assert_character(URL, null.ok = TRUE)

  # Constants ---------------------------------------------------------------
  xdate <- get_x_ms_date()
  verbosity <- if (verbose) verbose(TRUE, TRUE, TRUE, TRUE) else NULL
  nobody <- if (verb == "HEAD") config(nobody = TRUE) else NULL
  URL <- if (!is.null(URL)) {
    URL
  } else {
    get_azure_storage_url(storage_account, container, blob)
  }

  base_xheaders <- c(
    "x-ms-date" = xdate,
    "x-ms-version" = "2017-04-17",
    "Content-Length" = get_content_length(body_content),
    "Content-Type" = get_content_type(body_content)
  )

  # Get Shared Signature Key ------------------------------------------------
  shared_key <- get_signature(
    verb = verb, storage_account = storage_account, storage_key = storage_key,
    container = container, blob = blob,
    query = query, xheaders = c(base_xheaders, xheaders), verbose = verbose
  )

  # Request -----------------------------------------------------------------
  VERB(verb, URL, query = query, body = body_content, add_headers(
    Authorization = shared_key,
    .headers = c(base_xheaders, xheaders) %>% unlist
  ), verbosity, nobody)
}
